language: node_js

node_js:
  - "4.1"

install:
  - npm install

script:
  - npm run test-mocha
  - npm run test-css
  - npm run test-js

addons:
    code_climate:
        repo_token: 21b900d6bc4dee90cac3d95ded6e1b92ad9d8f497cefbd5cf4ecf0e601abdc54